permalink: /:year:month:day/:title
url: https://sonjhing.github.io
baseurl: ""

# variables
name: sonjhing's Blog
description: sonjhing's personal blog
google_verification: null


# File management
include: [".htaccess"]
exclude:
  - README.md
  - LICENSE
  - node_modules
  - package.json
  - package-lock.json
  - pnpm-lock.yaml
  - astro.config.mjs
  - tsconfig.json
  - src
  - public
  - .prettierrc
  - .node-version
  - env.example
  - .env.sample
  - ARCHITECTURE.md
  - CONTENT_PROVIDERS.md
  - SUPPORT.md
  - sfasfasf.txt
  - gull2.jpg

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true